server.port: 7100

spring:
  application.name: board
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 1q2w3e4r%T
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
