server.port: 8082

url:
  boardUrl: http://localhost:7100
  todoUrl: http://localhost:7101

---
spring.profiles: dev

url:
  boardUrl: http://localhost:7100
  todoUrl: http://localhost:7101

---
spring:
  profiles: prod

url:
  boardUrl: http://localhost:7100
  todoUrl: http://localhost:7101
